#!/usr/bin/bash

# Create virtualenv if does not exists and install dependencies
if [ ! -d venv ]; then
  python3 -m virtualenv venv
fi

source venv/bin/activate
pip install -r backend/requirements.txt

python3 deploy/deploy.py
