#!/usr/bin/bash

# Create virtualenv if does not exists and install dependencies
if [ ! -d venv ]; then
  echo "Virtual Environment does not exist, creating virtual environment..."
  python3 -m virtualenv venv
fi

echo "Building frontend..."
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"                   # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion
cd frontend/ || exit
npm install --production
npm run build --production
echo "Done building frontend!"

echo "Starting backend..."
cd ..
source venv/bin/activate
pip install -r backend/requirements.txt

python3 deploy/deploy.py
echo "Deployment complete!"
